### ISSUE TITLE
Bug in src/protocol.h

### ISSUE THREAD

**Issue by ddirt** [solarcoin/solarcoin-legacy-pow-wallet#2]
The default P2P and RPC ports are both set to 18188. Line 22 in protocol h is currently:
    return testnet ? 28188 : 18188;

according to the readme file, that should actually be 
    return testnet ? 28188 : 18181;

otherwise solarcoind terminates with bind error on launch unless user sets alternate rpcport. Suggest changing P2P port to 18181 in protocol.h or changing RPC port to 18181 in bitcoinrpc.cpp

**Comment by solarcoin** [comment]
Corrected.  Thanks!
